### ISSUE TITLE
Split utilsac into separate projects

### ISSUE THREAD

**Issue by GrosSacASac** [GrosSacASac/utilsac#4]
- [x] files.js 	into filesac
- [x] operators.js 	into operatorsac
- [x] random.js 	into randomsac
- [x] utility.js 	stays utilsac
- [x] blobs.js  into utilisac (extras)

**Comment by GrosSacASac** [comment]
https://github.com/GrosSacASac/filesac

**Comment by GrosSacASac** [comment]
https://github.com/GrosSacASac/randomsac

**Comment by GrosSacASac** [comment]
https://github.com/GrosSacASac/operatorsac

**Comment by GrosSacASac** [comment]
- [ ] deep.js into deep-sac
- [ ] evalGlobal into eval-sac
- [ ] remove blob (put link in the changelog)
- [ ] typecast into type-sac

**Comment by GrosSacASac** [comment]
closing for now, here's my thoughts
**Pro**

- Single responsibility principle
- Clean

**Not true anymore**

- Dead code : Any modern application uses treeshaking

**Contra**

- Easier to manage monorepo
- Would have to update depending projects eventually
